site_name: Terraform Templates

theme:
  name: material
  features:
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
  language: en

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html

plugins:
  - search

nav:
  - Home: index.md
  - AWS: 
    - Github Action OIDC: aws/github_action_oidc.md
    - S3 Remote State: aws/s3_remote_state.md
    - Optuna SageMaker Studio: aws/optuna_sagemaker_studio.md
    - Sagemaker Studio: aws/sagemaker_studio.md
    - Cross-Platform Terraform Lockfile: aws/terraform_lockfile_cross_platform.md
